server:
  port: 8081

spring:
  application:
    name: auth-service
    
  config:
    import: optional:configserver:http://localhost:8888/

springdoc:
  swagger-ui:
    config-url: /auth-service/v3/api-docs/swagger-config
    url: /auth-service/v3/api-docs
