server:
  port: 8083
spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://localhost:8888/
    
springdoc:
  swagger-ui:
    config-url: /auth-service/v3/api-docs/swagger-config
    url: /auth-service/v3/api-docs